//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PI_Searchfood.wsServicios {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsServiciosSoap", Namespace="http://tempuri.org/")]
    public partial class wsServicios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getComidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getComida_XMLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsServicios() {
            this.Url = global::PI_Searchfood.Properties.Settings.Default.PI_Searchfood_wsServicios_wsServicios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getComidaCompletedEventHandler getComidaCompleted;
        
        /// <remarks/>
        public event getComida_XMLCompletedEventHandler getComida_XMLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getComida", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getComida() {
            object[] results = this.Invoke("getComida", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getComidaAsync() {
            this.getComidaAsync(null);
        }
        
        /// <remarks/>
        public void getComidaAsync(object userState) {
            if ((this.getComidaOperationCompleted == null)) {
                this.getComidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetComidaOperationCompleted);
            }
            this.InvokeAsync("getComida", new object[0], this.getComidaOperationCompleted, userState);
        }
        
        private void OngetComidaOperationCompleted(object arg) {
            if ((this.getComidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getComidaCompleted(this, new getComidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getComida_XML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clstbComida[] getComida_XML() {
            object[] results = this.Invoke("getComida_XML", new object[0]);
            return ((clstbComida[])(results[0]));
        }
        
        /// <remarks/>
        public void getComida_XMLAsync() {
            this.getComida_XMLAsync(null);
        }
        
        /// <remarks/>
        public void getComida_XMLAsync(object userState) {
            if ((this.getComida_XMLOperationCompleted == null)) {
                this.getComida_XMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetComida_XMLOperationCompleted);
            }
            this.InvokeAsync("getComida_XML", new object[0], this.getComida_XMLOperationCompleted, userState);
        }
        
        private void OngetComida_XMLOperationCompleted(object arg) {
            if ((this.getComida_XMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getComida_XMLCompleted(this, new getComida_XMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clstbComida {
        
        private long longcomiCodigoField;
        
        private clstbCategoria obclstbCategoriaField;
        
        private clstbRestaurante obclstbRestauranteField;
        
        private long loncomiValorField;
        
        private string strcomiDescripcionField;
        
        private string strcomiRutaImagenField;
        
        /// <remarks/>
        public long longcomiCodigo {
            get {
                return this.longcomiCodigoField;
            }
            set {
                this.longcomiCodigoField = value;
            }
        }
        
        /// <remarks/>
        public clstbCategoria obclstbCategoria {
            get {
                return this.obclstbCategoriaField;
            }
            set {
                this.obclstbCategoriaField = value;
            }
        }
        
        /// <remarks/>
        public clstbRestaurante obclstbRestaurante {
            get {
                return this.obclstbRestauranteField;
            }
            set {
                this.obclstbRestauranteField = value;
            }
        }
        
        /// <remarks/>
        public long loncomiValor {
            get {
                return this.loncomiValorField;
            }
            set {
                this.loncomiValorField = value;
            }
        }
        
        /// <remarks/>
        public string strcomiDescripcion {
            get {
                return this.strcomiDescripcionField;
            }
            set {
                this.strcomiDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public string strcomiRutaImagen {
            get {
                return this.strcomiRutaImagenField;
            }
            set {
                this.strcomiRutaImagenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clstbCategoria {
        
        private long longcateCodigoField;
        
        private string strcateDescripcionField;
        
        /// <remarks/>
        public long longcateCodigo {
            get {
                return this.longcateCodigoField;
            }
            set {
                this.longcateCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string strcateDescripcion {
            get {
                return this.strcateDescripcionField;
            }
            set {
                this.strcateDescripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsUsuarios {
        
        private int inCodigoField;
        
        private string stDescripcionField;
        
        private string stLoginField;
        
        private string stPasswordField;
        
        private int stPerfilField;
        
        private string stImagenField;
        
        /// <remarks/>
        public int inCodigo {
            get {
                return this.inCodigoField;
            }
            set {
                this.inCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string stDescripcion {
            get {
                return this.stDescripcionField;
            }
            set {
                this.stDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public string stLogin {
            get {
                return this.stLoginField;
            }
            set {
                this.stLoginField = value;
            }
        }
        
        /// <remarks/>
        public string stPassword {
            get {
                return this.stPasswordField;
            }
            set {
                this.stPasswordField = value;
            }
        }
        
        /// <remarks/>
        public int stPerfil {
            get {
                return this.stPerfilField;
            }
            set {
                this.stPerfilField = value;
            }
        }
        
        /// <remarks/>
        public string stImagen {
            get {
                return this.stImagenField;
            }
            set {
                this.stImagenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clstbPais {
        
        private long longpaisCodigoField;
        
        private string stpaisNombreField;
        
        /// <remarks/>
        public long longpaisCodigo {
            get {
                return this.longpaisCodigoField;
            }
            set {
                this.longpaisCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string stpaisNombre {
            get {
                return this.stpaisNombreField;
            }
            set {
                this.stpaisNombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clstbDepartamento {
        
        private long longdepaCodigoField;
        
        private string stdepaCombreField;
        
        private clstbPais clstbPaisField;
        
        /// <remarks/>
        public long longdepaCodigo {
            get {
                return this.longdepaCodigoField;
            }
            set {
                this.longdepaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string stdepaCombre {
            get {
                return this.stdepaCombreField;
            }
            set {
                this.stdepaCombreField = value;
            }
        }
        
        /// <remarks/>
        public clstbPais clstbPais {
            get {
                return this.clstbPaisField;
            }
            set {
                this.clstbPaisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clstbCiudad {
        
        private long ciudCodigoField;
        
        private string ciudNombreField;
        
        private clstbDepartamento clstbDepartamentoField;
        
        /// <remarks/>
        public long ciudCodigo {
            get {
                return this.ciudCodigoField;
            }
            set {
                this.ciudCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string ciudNombre {
            get {
                return this.ciudNombreField;
            }
            set {
                this.ciudNombreField = value;
            }
        }
        
        /// <remarks/>
        public clstbDepartamento clstbDepartamento {
            get {
                return this.clstbDepartamentoField;
            }
            set {
                this.clstbDepartamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clstbRestaurante {
        
        private long longrestCodigoField;
        
        private string strrestNombreField;
        
        private string strrestDireccionField;
        
        private string strrestTelefonoField;
        
        private string strrestDescripcionField;
        
        private string strrestLatitudField;
        
        private string strrestLongitudField;
        
        private string strrestcorreoField;
        
        private clstbCiudad clstbCiudadField;
        
        private clsUsuarios clsUsuariosField;
        
        private string strrestPrincipalField;
        
        private string strrestSucursalField;
        
        /// <remarks/>
        public long longrestCodigo {
            get {
                return this.longrestCodigoField;
            }
            set {
                this.longrestCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string strrestNombre {
            get {
                return this.strrestNombreField;
            }
            set {
                this.strrestNombreField = value;
            }
        }
        
        /// <remarks/>
        public string strrestDireccion {
            get {
                return this.strrestDireccionField;
            }
            set {
                this.strrestDireccionField = value;
            }
        }
        
        /// <remarks/>
        public string strrestTelefono {
            get {
                return this.strrestTelefonoField;
            }
            set {
                this.strrestTelefonoField = value;
            }
        }
        
        /// <remarks/>
        public string strrestDescripcion {
            get {
                return this.strrestDescripcionField;
            }
            set {
                this.strrestDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public string strrestLatitud {
            get {
                return this.strrestLatitudField;
            }
            set {
                this.strrestLatitudField = value;
            }
        }
        
        /// <remarks/>
        public string strrestLongitud {
            get {
                return this.strrestLongitudField;
            }
            set {
                this.strrestLongitudField = value;
            }
        }
        
        /// <remarks/>
        public string strrestcorreo {
            get {
                return this.strrestcorreoField;
            }
            set {
                this.strrestcorreoField = value;
            }
        }
        
        /// <remarks/>
        public clstbCiudad clstbCiudad {
            get {
                return this.clstbCiudadField;
            }
            set {
                this.clstbCiudadField = value;
            }
        }
        
        /// <remarks/>
        public clsUsuarios clsUsuarios {
            get {
                return this.clsUsuariosField;
            }
            set {
                this.clsUsuariosField = value;
            }
        }
        
        /// <remarks/>
        public string strrestPrincipal {
            get {
                return this.strrestPrincipalField;
            }
            set {
                this.strrestPrincipalField = value;
            }
        }
        
        /// <remarks/>
        public string strrestSucursal {
            get {
                return this.strrestSucursalField;
            }
            set {
                this.strrestSucursalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getComidaCompletedEventHandler(object sender, getComidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getComidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getComidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getComida_XMLCompletedEventHandler(object sender, getComida_XMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getComida_XMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getComida_XMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clstbComida[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clstbComida[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591