//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_SearchfoodF.MVC.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbIncidencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbIncidencia()
        {
            this.tbIncidencia_Comentarios = new HashSet<tbIncidencia_Comentarios>();
        }
    
        public int Id { get; set; }
        public Nullable<long> Identificacion { get; set; }
        [DisplayName("Primer Nombre")]
        public string primer_nombre { get; set; }
        [DisplayName("Segundo Nombre")]
        public string segundo_nombrre { get; set; }
        [DisplayName("Primer Apellido")]
        public string primer_apellido { get; set; }
        [DisplayName("Segundo Apellido")]
        public string segundo_apellido { get; set; }
        [DisplayName("Dirección")]
        public string direccion { get; set; }
        [DisplayName("Teléfono")]
        public string telefono { get; set; }
        [DisplayName("Correo")]
        public string correo { get; set; }
        [DisplayName("Estado Incidencia")]
        public Nullable<int> Estado_Indicencia { get; set; }
        [DisplayName("Tipo Incidencia")]
        public Nullable<int> Tipo_Incidencia { get; set; }
    
        public virtual tbEstado_Incidencia tbEstado_Incidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbIncidencia_Comentarios> tbIncidencia_Comentarios { get; set; }
        public virtual tbTipoIncidencia tbTipoIncidencia { get; set; }
    }
}
