//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Searchfood.Logica.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_SEARCHFOODEntities1 : DbContext
    {
        public BD_SEARCHFOODEntities1()
            : base("name=BD_SEARCHFOODEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbbonus> tbbonus { get; set; }
        public virtual DbSet<tbCategorias> tbCategorias { get; set; }
        public virtual DbSet<tbciudad> tbciudad { get; set; }
        public virtual DbSet<tbdepartamento> tbdepartamento { get; set; }
        public virtual DbSet<tbgenero> tbgenero { get; set; }
        public virtual DbSet<tbpais> tbpais { get; set; }
        public virtual DbSet<tbperfiles> tbperfiles { get; set; }
        public virtual DbSet<tbpersona> tbpersona { get; set; }
        public virtual DbSet<tbreservas> tbreservas { get; set; }
        public virtual DbSet<tbreservasDetalle> tbreservasDetalle { get; set; }
        public virtual DbSet<tbrestaurante> tbrestaurante { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbComida> tbComida { get; set; }
    }
}
