//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Searchfood.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbComida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbComida()
        {
            this.tbreservasDetalle = new HashSet<tbreservasDetalle>();
        }
    
        public decimal comiCodigo { get; set; }
        public decimal cateCodigo { get; set; }
        public decimal restcodigo { get; set; }
        public decimal comiValor { get; set; }
        public string comiDescripcion { get; set; }
        public string comiRutaImagen { get; set; }
    
        public virtual tbCategorias tbCategorias { get; set; }
        public virtual tbrestaurante tbrestaurante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbreservasDetalle> tbreservasDetalle { get; set; }
    }
}
