//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Searchfood.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbpersona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbpersona()
        {
            this.tbbonus = new HashSet<tbbonus>();
            this.tbreservas = new HashSet<tbreservas>();
        }
    
        public decimal persIdentificacion { get; set; }
        public string persNombre { get; set; }
        public string persApellido { get; set; }
        public string persDireccion { get; set; }
        public string persCorreo { get; set; }
        public string persCelular { get; set; }
        public decimal geneCodigo { get; set; }
        public decimal ciudCodigo { get; set; }
        public decimal usuaCodigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbbonus> tbbonus { get; set; }
        public virtual tbciudad tbciudad { get; set; }
        public virtual tbgenero tbgenero { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbreservas> tbreservas { get; set; }
    }
}
