//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Searchfood.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbreservas
    {
        public decimal restCodigo { get; set; }
        public Nullable<decimal> persIdentificacion { get; set; }
        public decimal reseCodigo { get; set; }
        public Nullable<System.DateTime> reseFecha { get; set; }
        public Nullable<decimal> estaCodigo { get; set; }
        public Nullable<decimal> reseTotal { get; set; }
        public Nullable<decimal> reseImpuesto { get; set; }
        public string reseObservacion { get; set; }
    
        public virtual tbpersona tbpersona { get; set; }
        public virtual tbrestaurante tbrestaurante { get; set; }
    }
}
