//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Searchfood.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbrestaurante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbrestaurante()
        {
            this.tbbonus = new HashSet<tbbonus>();
            this.tbreservas = new HashSet<tbreservas>();
            this.tbreservasDetalle = new HashSet<tbreservasDetalle>();
            this.tbComida = new HashSet<tbComida>();
        }
    
        public decimal restCodigo { get; set; }
        public string restNombre { get; set; }
        public string restDireccion { get; set; }
        public string restTelefono { get; set; }
        public string restDescripcion { get; set; }
        public string restLatitud { get; set; }
        public string restLongitud { get; set; }
        public decimal ciudCodigo { get; set; }
        public decimal usuaCodigo { get; set; }
        public string restCorreo { get; set; }
        public string restPrincipal { get; set; }
        public string restSucursal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbbonus> tbbonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbreservas> tbreservas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbreservasDetalle> tbreservasDetalle { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbComida> tbComida { get; set; }
    }
}
